name: Build ARM32 Node.js Addon

on:
  push:
    branches: [main]

jobs:
  build-arm32:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 make g++ gcc libc6-dev-armhf-cross g++-arm-linux-gnueabihf

    - name: Install Node-gyp Globally
      run: npm install -g node-gyp



    - name: Configure Node-gyp for ARM32
      env:
        CC: arm-linux-gnueabihf-gcc
        CXX: arm-linux-gnueabihf-g++
      run: node-gyp configure --arch=arm

    - name: Build Addon
      env:
        CC: arm-linux-gnueabihf-gcc
        CXX: arm-linux-gnueabihf-g++
      run: node-gyp build

    - name: Upload ARM32 Build
      uses: actions/upload-artifact@v4
      with:
        name: addon-arm32
        path: build/Release/addon.node